[book]
authors = ["windmissing", "poloog"]
language = "en"
description = "The note of GAMES101"
multilingual = false
src = "src"
title = "GAMES101"

[preprocessor.pagetoc]

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/CaterpillarStudyGroup/GAMES101_mdbook"
git-repository-icon = "fa-github"
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]

[output.html.fold]

[output.html.print]
enable = true

[output.html.search]
enable = true
